import Link from "next/link";
import { releaseTag, tours } from "./catalog";

export const metadata = {
  title: "Tested guided tours — vmsh",
  description: "Replay behavior-tested vmsh sessions as guided terminal lessons.",
};

export default function ToursPage() {
  return (
    <main className="tour-page">
      <header className="site-header">
        <Link className="vmsh-logo" href="/" aria-label="vmsh home">
          <span className="prompt-mark">&gt;_</span>
          <span>vmsh</span>
        </Link>
        <nav aria-label="Tour navigation"><Link href="/">Downloads</Link></nav>
      </header>

      <section className="tour-hero">
        <p className="kicker"><span /> TESTED DOCUMENTATION</p>
        <h1>Learn vmsh from sessions that actually passed.</h1>
        <p>
          Every lesson is generated by driving a real interactive vmsh session and
          checking the behavior it teaches. Released lessons are tied to {releaseTag}.
        </p>
      </section>

      <section className="tour-catalog" aria-labelledby="tour-catalog-heading">
        <p className="kicker"><span /> GUIDED TOURS</p>
        <h2 id="tour-catalog-heading">Choose a workflow</h2>
        <ul>
          {tours.map((tour) => (
            <li key={tour.id}>
              <Link href={`/tours/${tour.id}`}>
                <span>{tour.released ? `Release ${releaseTag}` : "Unreleased preview"}</span>
                <strong>{tour.title}</strong>
                <p>{tour.description}</p>
              </Link>
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}
